=== HtmlUnit/htmlunit/src/main/resources/com/gargoylesoftware/htmlunit/javascript/configuration/JavaScriptConfiguration.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:annotation>
	  <xsd:documentation xml:lang="en">
	   JavaScript Configuration Schema for HtmlUnit
	  </xsd:documentation>
	</xsd:annotation>

	<xsd:element name="configuration" type="configurationType"/>

	<xsd:complexType name="configurationType">
		<xsd:sequence>
			<xsd:element name="doclink" type="doclinkType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="class" type="classType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="doclinkType">
		<xsd:attribute name="url" type="xsd:string" use="required"/>
		<xsd:attribute name="descr" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="classType">
		<xsd:sequence>
			<xsd:element name="doclink" type="doclinkType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="browser" type="requiredBrowserType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="constant" type="constantType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="property" type="propertyType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="function" type="functionType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="notImplemented" type="xsd:boolean" default="false"/>
		<xsd:attribute name="classname" type="xsd:string" use="required"/>
		<xsd:attribute name="jsConstructor" type="xsd:string"/>
		<xsd:attribute name="htmlClass" type="xsd:string"/>
		<xsd:attribute name="JSObject" type="xsd:boolean" default="false"/>
		<xsd:attribute name="extends" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="constantType">
		<xsd:sequence>
			<xsd:element name="browser" type="requiredBrowserType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="propertyType">
		<xsd:sequence>
			<xsd:element name="doclink" type="doclinkType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="browser" type="requiredBrowserType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="notImplemented" type="xsd:boolean" default="false"/>
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="readable" type="xsd:boolean" default="true"/>
		<xsd:attribute name="writable" type="xsd:boolean" default="true"/>
	</xsd:complexType>

	<xsd:complexType name="functionType">
		<xsd:sequence>
			<xsd:element name="doclink" type="doclinkType" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="browser" type="requiredBrowserType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="notImplemented" type="xsd:boolean" default="false"/>
	</xsd:complexType>

	<xsd:complexType name="requiredBrowserType">
		<xsd:attribute name="name" use="required">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="Firefox"/>
					<xsd:enumeration value="Internet Explorer"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="min-version" type="xsd:float"/>
		<xsd:attribute name="max-version" type="xsd:float"/>
	</xsd:complexType>
</xsd:schema>

=== HtmlUnit/htmlunit/src/main/resources/com/gargoylesoftware/htmlunit/javascript/configuration/JavaScriptConfiguration.xml
<?xml version="1.0"?>
<configuration
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="JavaScriptConfiguration.xsd">

    <doclink
        url="http://www.w3.org/DOM/"
        descr="W3C Document Object Model (DOM) - Start"/>
    <doclink
        url="http://www.w3.org/DOM/TR/"
        descr="W3C Document Object Model (DOM) - Technical Reports"/>
    <doclink
        url="http://www.mozilla.org/docs/dom/"
        descr="The Document Object Model in Mozilla"/>
    <doclink
        url="http://msdn.microsoft.com/en-us/library/ms533050.aspx"
        descr="HTML and DHTML Reference on MSDN"/>

    <class name="ActiveXObject" classname="com.gargoylesoftware.htmlunit.javascript.host.ActiveXObject"
        jsConstructor="jsConstructor" JSObject="true">
        <browser name="Microsoft Internet Explorer" min-version="4"/>
    </class>

    <class name="Attr" classname="com.gargoylesoftware.htmlunit.javascript.host.Attr"
        JSObject="true" htmlClass="com.gargoylesoftware.htmlunit.html.DomAttr">
        <property name="expando" readable="true" writable="false"/>
        <property name="firstChild" readable="true" writable="false"/>
        <property name="lastChild" readable="true" writable="false"/>
        <property name="name" readable="true" writable="false"/>
        <property name="nextSibling" readable="true" writable="false"/>
        <property name="nodeName" readable="true" writable="false"/>
        <property name="nodeType" readable="true" writable="false"/>
        <property name="nodeValue" readable="true" writable="false"/>
        <property name="ownerDocument" readable="true" writable="false"/>
        <property name="parentNode" readable="true" writable="false"/>
        <property name="previousSibling" readable="true" writable="false"/>
        <property name="specified" readable="true" writable="false"/>
        <property name="value" readable="true" writable="true"/>
    </class>

    <class name="BoxObject" classname="com.gargoylesoftware.htmlunit.javascript.host.BoxObject" JSObject="true">
        <property name="element" readable="true" writable="false"/>
        <property name="firstChild" readable="true" writable="false"/>
        <property name="lastChild" readable="true" writable="false"/>
        <property name="nextSibling" readable="true" writable="false"/>
        <property name="previousSibling" readable="true" writable="false"/>
        <property name="screenX" readable="true" writable="false"/>
        <property name="screenY" readable="true" writable="false"/>
        <property name="x" readable="true" writable="false"/>
        <property name="y" readable="true" writable="false"/>
        <property name="width" readable="true" writable="false"/>
        <property name="height" readable="true" writable="false"/>
    </class>

    <class name="CharacterDataImpl" extends="Node" classname="com.gargoylesoftware.htmlunit.javascript.host.CharacterDataImpl"
        JSObject="true" htmlClass="com.gargoylesoftware.htmlunit.html.DomCharacterData">
        <property name="data" readable="true" writable="true"/>
        <property name="length" readable="true" writable="false"/>
        <property name="tabIndex" notImplemented="true" readable="true" writable="true"/>

        <function name="appendData"/>
        <function name="deleteData"/>
        <function name="insertData"/>
        <function name="replaceData"/>
        <function name="substringData"/>
    </class>

    <class name="ComputedCSSStyleDeclaration" extends="CSSStyleDeclaration" classname="com.gargoylesoftware.htmlunit.javascript.host.ComputedCSSStyleDeclaration"
        JSObject="true">
    </class>

    <class name="CSSRule" classname="com.gargoylesoftware.htmlunit.javascript.host.CSSRule" JSObject="false">
        <constant name="UNKNOWN_RULE">
            <browser name="Firefox"/>
        </constant>
        <constant name="STYLE_RULE">
            <browser name="Firefox"/>
        </constant>
        <constant name="CHARSET_RULE">
            <browser name="Firefox"/>
        </constant>
        <constant name="IMPORT_RULE">
            <browser name="Firefox"/>
        </constant>
        <constant name="MEDIA_RULE">
            <browser name="Firefox"/>
        </constant>
        <constant name="FONT_FACE_RULE">
            <browser name="Firefox"/>
        </constant>
        <constant name="PAGE_RULE">
            <browser name="Firefox"/>
        </constant>
        <property name="type" readable="true" writable="false">
            <browser name="Firefox"/>
        </property>
        <property name="cssText" readable="true" writable="true">
            <browser name="Firefox"/>
        </property>
        <property name="parentStyleSheet" readable="true" writable="false">
            <browser name="Firefox"/>
        </property>
        <property name="parentRule" readable="true" writable="false">
            <browser name="Firefox"/>
        </property>
        <property name="readOnly" notImplemented="true" readable="true" writable="false">
            <browser name="Microsoft Internet Explorer"/>
        </property>
    </class>

    <class name="CSSRuleList" classname="com.gargoylesoftware.htmlunit.javascript.host.CSSRuleList" JSObject="true">
        <property name="length" readable="true" writable="false"/>
        <function name="item">
            <browser name="Firefox"/>
        </function>
    </class>

    <class name="CSSStyleDeclaration" classname="com.gargoylesoftware.htmlunit.javascript.host.CSSStyleDeclaration" JSObject="true">
        <property name="azimuth" readable="true" writable="true">
            <browser name="Firefox"/>
        </property>
        <property name="background" readable="true" writable="true"/>
        <property name="backgroundAttachment" readable="true" writable="true"/>
        <property name="backgroundColor" readable="true" writable="true"/>
        <property name="backgroundImage" readable="true" writable="true"/>
        <property name="backgroundPosition" readable="true" writable="true"/>
        <property name="backgroundPositionX" readable="true" writable="true">
            <browser name="Microsoft Internet Explorer"/>
        </property>
        <property name="backgroundPositionY" readable="true" writable="true">
            <browser name="Microsoft Internet Explorer"/>
        </property>
        <property name="backgroundRepeat" readable="true" writable="true"/>
        <property name="behavior" readable="true" writable="true">
            <browser name="Microsoft Internet Explorer"/>
        </property>
        <property name="border" readable="true" writable="true"/>
        <property name="borderBottom" readable="true" writable="true"/>
        <property name="borderBottomColor" readable="true" writable="true"/>
        <property name="borderBottomStyle" readable="true" writable="true"/>
        <property name="borderBottomWidth" readable="true" writable="true"/>
        <property name="borderCollapse" readable="true" writable="true"/>
        <property name="borderColor" readable="true" writable="true"/>
        <property name="borderLeft" readable="true" writable="true"/>
        <property name="borderLeftColor" readable="true" writable="true"/>
        <property name="borderLeftStyle" readable="true" writable="true"/>
        <property name="borderLeftWidth" readable="true" writable="true"/>
        <property name="borderRight" readable="true" writable="true"/>
        <property name="borderRightColor" readable="true" writable="true"/>
        <property name="borderRightStyle" readable="true" writable="true"/>
        <property name="borderRightWidth" readable="true" writable="true"/>
        <property name="borderSpacing" readable="true" writable="true">
            <browser name="Firefox"/>
        </property>
        <property name="borderStyle" readable="true" writable="true"/>
        <property name="borderTop" readable="true" writable="true"/>
        <property name="borderTopColor" readable="true" writable="true"/>
        <property name="borderTopStyle" readable="true" writable="true"/>
        <property name="borderTopWidth" readable="true" writable="true"/>
        <property name="borderWidth" readable="true" writable="true"/>
        <property name="bottom" readable="true" writable="true"/>
        <property name="captionSide" readable="true" writable="true">
            <browser name="Firefox"/>
        </property>
        <property name="clear" readable="true" writable="true"/>
        <property name="clip" readable="true" writable="true"/>
        <property name="color" readable="true" writable="true"/>
        <property name="content" readable="true" writable="true">
            <browser name="Firefox"/>
        </property>
        <property name="counterIncrement" readable="true" writable="true">
            <browser name="Firefox"/>
        </property>
        <property name="counterReset" readable="true" writable="true">
            <browser name="Firefox"/>
        </property>
        <property name="cssFloat" readable="true" writable="true">
            <browser name="Firefox"/>
        </property>
        <property name="cssText" readable="true" writable="true"/>
        <property name="cue" readable="true" writable="true">
            <browser name="Firefox"/>
        </property>
        <property name="cueAfter" readable="true" writable="true">
            <browser name="Firefox"/>
        </property>
        <property name="cueBefore" readable="true" writable="true">
            <browser name="Firefox"/>
        </property>
        <property name="cursor" readable="true" writable="true"/>
        <property name="direction" readable="true" writable="true"/>
        <property name="display" readable="true" writable="true"/>
        <property name="elevation" readable="true" writable="true">
            <browser name="Firefox"/>
        </property>
